### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by hantuzun** [suggestgrid/suggestgrid-js#7]

**Comment by mac2000** [comment]
Why this issue is closed and will it be fixed?

At moment it does not possible to perform direct calls to rest api because of preflight options requests did not pass

**Comment by hantuzun** [comment]
Hi @mac2000,

This issue was fixed, I'll review it again in 2 hours.

**Comment by mac2000** [comment]
In case it will help, here is example:

```
curl -i -XOPTIONS https://private:3c907486720bc6872e359ed8b97b548c@eu-north.suggestgrid.space/9a9c3366-88d6-4647-bbe0-bdece0cc8b95/v1/types
```

which immediately will give you `HTTP/1.1 405 Method Not Allowed`

it is not critical at all for me, just looking around for different implementations, hope it will help you make your system better

BR
Alex

**Comment by mac2000** [comment]
Here is use case: suppose I do have access to google tag manager and going to perform experiment on live site just by adding pieces of javascript code to it, so I may integrate site with suggestgrid without touching backend/developers/ops

without options header it not possible at all, so at this moment only possible way for me is to deploy separate app somewhere which will proxy requests from users browser into sengrid, but if I can do that and forced to do it then why I need sendgrid at all

something like that, hope it help

**Comment by hantuzun** [comment]
I see your case Alex.

I'll be closing this issue and opening another one titled "Support CORS Preflight Requests"
